# **Numpy**

In [6]:
import numpy as np

# Create 1D array
arr = np.arange(10, 30) # Changed the range
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(30, 50) # Changed the range
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

1D Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
4x5 Matrix:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Mean: 19.5
Median: 19.5
Standard Deviation: 5.766281297335398
Addition: [40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78]
Multiplication: [ 300  341  384  429  476  525  576  629  684  741  800  861  924  989
 1056 1125 1196 1269 1344 1421]


In [3]:
import numpy as np

# Create 1D array
arr = np.arange(1, 21)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(21, 41)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
4x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Addition: [22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]
Multiplication: [ 21  44  69  96 125 156 189 224 261 300 341 384 429 476 525 576 629 684
 741 800]
